reddit:
  postfix: .json
  groups:
    de:
      - https://www.reddit.com/r/kreiswichs/
      - https://www.reddit.com/r/ich_iel/
    ru:
      - https://www.reddit.com/r/Pikabu/comments/cvdafl/%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B5_%D0%BC%D0%B5%D0%BC%D1%8B_%D0%B1%D0%B5%D1%81%D0%BF%D0%BE%D0%B4%D0%BE%D0%B1%D0%BD%D1%8B/ey3q3tr/
      - https://www.reddit.com/r/Pikabu/